# Site wide configuration

title: I know what I'm doing
locale: en_US
description: Keep the innovations, events and thoughs for sharing and reviewing
logo: profile.jpg
search: true
host: 0.0.0.0

# Plugins
gems:
  - jekyll-sitemap

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site owner
owner:
  name: 何聪辉
  avatar: profile.jpg
  email: heconghui@email.com
  disqus-shortname: 'conghui'
  twitter: #username
  facebook: #username
  github: conghui
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

# Handling Reading
exclude:      ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
